[package]
name = "exchange_test"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
serde = { version = "1.0.210", features = ["derive"] }
rust_decimal = "1.36"
rust_decimal_macros = "1.36"